---
title: "Teaching"
output: html_document
---

- Winter Term 2021-2022: Statistic II, Lecture, Health and Medical University, Potsdam

- Winter Term 2021-2022: Exercise to the lecture Statistics II, Health and Medical University, Potsdam

- Oct. 2021: Linear mixed-effects models, invited Workshop at the Department for Information Systems, University of Innsbruck

- Summer Term 2021: Scientific working, Medical School Berlin

- Summer Term 2021: Scientific working, Health and Medical University, Potsdam

- Summer Term 2021: Seminar Research Methods 2, Health and Medical University, Potsdam

- Feb. 2021: Power analyses for linear mixed-effects models, invited Workshop at the Potsdam Embodied Cognition Group, University of Potsdam

- Winter Term 2020-2021: Scientific working, Health and Medical University Potsdam

- Summer Term 2020: [Summer School on Statistical Methods for Linguists and Psychology (SMLP) 2020](https://vasishth.github.io/smlp2020/), Frequentist & Bayesian, Beginner & Advanced Tracks, co-taught with Prof. Dr. R. Kliegl, Prof. Dr. D. Bates, Dr. A. Bürki, Dr. B. Nicenboim, and Prof. Dr. S. Vasishth, University of Potsdam

- Fall Term 2020: Core Topics of Cognitive Science, co-taught with Prof. Dr. M. Postma, University of Tilburg

- Spring Term 2020: Statistics I, Lecture + practical session co-taught with Prof. Dr. T. Wiltshire, University of Tilburg

- Spring Term 2020: Research Workshop, Practical seminar co-taught with Prof. Dr. M. M. Jung, University of Tilburg

- Summer Term 2019: [Summer School on Statistical Methods for Linguists and Psychology (SMLP) 2019](https://vasishth.github.io/smlp2019/), Beginners and Advanced Frequentist and Bayesian Track, co-taught with Prof. Dr. D. Bates, Dr. A. Bürki, Dr. B. Nicenboim, Prof. Dr. R. Kliegl, and Prof. Dr. S. Vasishth, University of Potsdam

- Summer Term 2018: [Summer School on Statistical Methods for Linguists and Psychology (SMLP) 2018](https://vasishth.github.io/SMLP2018/), Frequentist Track, co-taught with Prof. Dr. R. Kliegl, Dr. A. Bürki, and Prof. Dr. S. Vasishth, University of Potsdam

- Winter Term 2017/18: Statistics with R, Seminar co-taught with Prof. Dr. R. Kliegl, University of Potsdam

- Summer Term 2017: Scientific working and writing, Seminar, University of Potsdam

- Winter Term 2016/17: Statistics with R, Seminar co-taught with Prof. Dr. R. Kliegl, University of Potsdam

- Summer Term 2016: Scientific working and writing, Seminar co-taught with Dr. S. Heinzel, University of Potsdam

- Winter Term 2015/16: Statistics with R, Seminar co-taught with Prof. Dr. R. Kliegl, University of Potsdam

- Oktober 2014: Mixed-effects modeling – Non-linear and random effects for models. R Workshop, Charité – Universitätsmedizin Berlin; selbst entwickelt

- Summer Term 2015: Random and mixed effects in statistical and computational modelling, Graduate Seminar, University of Potsdam

- Oct-Nov 2012: Mathematical models in neurocognitive psychology; Matlab tutorial as part of the lecture on interdisciplinary mathematics, co-taught with Prof. Dr. R. Engbert, University of Potsdam

- Oct 2012: Cognitive and Biological Psychology, Substitution for a session of the lecture by Prof. Dr. F. Rösler, University of Potsdam

- Sept 2009: Introduction to R: Descriptives, Graphics, and General Linear Model, Tutor in the tutorial by Prof. Dr. R. Kliegl, at the International Summer School „Eye Movements and EEG: Experimental Design, Technical Problems, and Statistical Analyses“, Beijing, China

- 2008 + 2010: Long night of sciences, Talks on cognitive psychology and eye movements; Lab tours

- 2010: Schiller High School: Introduction to “Cognitive Psychology and Mindless Reading”, incl. lab tour and supervising student presentations


